# https://github.com/actions/add-to-project
# PAT needs to be created and added to the repository as a secret (see instructions in link above)
# Update project URL below

name: Add all issues to repository project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/sas-institute-solutions-factory/projects/2
          github-token: ${{ secrets.ADD_ISSUE_TO_PROJECT_PAT }}
          #labeled: bug, needs-triage
          #label-operator: OR